### ISSUE TITLE
Todo bis 24.05

### ISSUE THREAD

**Issue by DavidDamke** [DavidDamke/Andoidapp#1]
- [ ] Videos über Layouts anschauen 
- [ ] Videos über Container anschauen 

- [ ] Layout und Container in Android Umsetzen
- [ ] Navigation Bar umsetzen
